baseURL = 'https://remix.roneo.app/'
languageCode = 'en-us'
defaultContentLanguage = 'en'


[params]
  title = '安身立家 | louzihan.ml'
  metaDescription = "懵懂少年到刚成家，期待未来"


# Languages
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
mark = "EN"

[Languages.zh]
languageName = "zh"
languageCode = "zh-hk"
contentDir = "content/zh-hk"
weight = 2
mark = "ZH"


[taxonomies]
  category= "theme"
  scene = "scenes"
